### ISSUE TITLE
The new version of defogging will cause a decrease in the brightness of the field of view

### ISSUE THREAD

**Issue by 1450143535** [Rumi727/Fix-Camera-Resolution#2]
Yes, I tried your new version of defogging today, and it did make the overall look unnatural. At the same time, I also found that when I set defogging to true, it makes the overall field of view brightness very dim, which greatly affects the gaming experience. Would it be possible to make slight adjustments or, like Sligili's defogging, only reduce the fog to almost invisible, so as to improve the field of view brightness to a certain extent and achieve defogging effect

**Comment by 1450143535** [comment]
To some extent, defogging has indeed been achieved, but at the same time, defogging also destroys the original brightness of the field of view. Take the Dine chart under the same weather conditions (flood) as an example
My field of view when using HDL mod：
![HDL](https://github.com/user-attachments/assets/e9182be5-82b7-426c-af14-2c9d8c5ebd92)
When I use the FixcameraResolution (1.1.0) mod：
![Fixcamera](https://github.com/user-attachments/assets/ae3698d1-c50e-47bf-bdc4-123aa5bbb179)

**Comment by Rumi727** [comment]
It's not that the actual game brightness has decreased, but the original game is dark, but it seems to be brightened by the light-colored fog.
So if you turn off the fog completely, it seems to become dark.
I found out about this issue yesterday, but I don't have time, so I'm going to fix it today.

By the way, I didn't know it would get that dark lol

**Comment by Rumi727** [comment]
While looking through the Unity API documentation, I found some interesting settings and applied them.
They came out really clean.

With the v1.2.1 update we added a Hide setting, which removes only part of the fog instead of completely removing it.

I uploaded it earlier v1.2.0 version has the same settings, but the implementation is slightly different because it was added before the API was discovered. (The brightness is preserved to some extent, but it is worse when there is a dine flood.)
